const question = require('./questions/questions');
const inquirer = require('inquirer');
const db = require('./db/connection');
const util = require('util');

// Create a promisified object variable for querying the database
const query = util.promisify(db.query).bind(db);

// Create an async function to initialize the application
const init = async () => {
  try {
    // Prompt the user with the question generated by askQuestion
    const answers = await inquirer.prompt(question.askQuestion(question.createList));
    const choice = answers.Choice;

  // Use switch statement to perform different actions based on user selection
  switch (choice) {
    case 1:
      viewAllEmployees();
      break;
    case 2:
      addEmployee();
      break;
    case 3:
      updateEmployeeRole();
      break;
    case 4:
      viewAllRoles();
      break;
    case 5:
      addRole();
      break;
    case 6:
      viewAllDepartments();
      break;
    case 7:
      addDepartment();
      break;
    case 8:
      console.log('Goodbye');
      process.exit();
    default:
      console.log('Invalid Choice');
    }
  } catch (err) {
    console.error(err);
  }
}

async function viewAllEmployees() {
    // Query the database to retrieve the specific columns I want displayed after joining tables
    const result = await query(`SELECT e.id, CONCAT(e.first_name, " ", e.last_name) AS name, r.title, d.name AS department, r.salary, CONCAT(e2.first_name, " ", e2.last_name) AS manager FROM employee AS e JOIN role AS r ON r.id = e.role_id LEFT JOIN employee AS e2 ON e.manager_id = e2.id JOIN department AS d ON d.id = r.department_id ORDER BY e.id`);
    
    // Display results as a table
    console.table(result);
    
    // Call the init function to keep the menu open for the user until they choose to quit
    init();
}

async function addEmployee() {
  // Query the database to get list of roles and managers
  const roles = await query('SELECT title AS name, id AS value FROM role');
  const manager = await query('SELECT CONCAT(first_name, " ", last_name) AS name, id AS value FROM employee WHERE manager_id IS null');
  // Add an option of 'No Manager' to the list
  manager.push({
    name: 'No Manager',
    value: null,
  });

  // Define the questions prompted to the user when they want to add an employee
  const questions = [
    {
      type: 'input',
      name: 'first_name',
      message: `Please enter the employee's first name:`
    },
    {
      type: 'input',
      name: 'last_name',
      message: `Please enter the employee's last name:`
    },
    {
      type: 'list',
      name: 'role_id',
      message: `Please enter the ID number of the employee's role:`,
      choices: roles,
    },
    {
      type: 'list',
      name: 'manager_id',
      message: `Please enter the ID number of the employee's manager:`,
      choices: manager,
    }
  ];

  // Prompt the user for employee information and store the responses
  const { first_name, last_name, role_id, manager_id } = await inquirer.prompt(questions);

  // Insert the new employees information into the database
  await query(
    `INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES(?, ?, ?, ?)`,
    [first_name, last_name, role_id, manager_id]
  );
  
  // Display a success message
  console.log(`${first_name} ${last_name} has been added to the employee database!`);

  // Call the viewAllEmployees function to display the table with the new addition and return to main menu
  viewAllEmployees();
}

async function updateEmployeeRole() {
  // Query the database for employee, role, and manager information
  const employee = await query('SELECT CONCAT(first_name, " ", last_name) AS name, id AS value FROM employee');
  const role = await query('SELECT title AS name, id AS value FROM role');
  const manager = await query('SELECT CONCAT(first_name, " ", last_name) AS name, id AS value FROM employee WHERE manager_id IS null');
  manager.push({
    name: 'No Manager',
    value: null,
  });
  // Define the questions to prompt the user for updating employee role
  const questions = [
    {
      type: 'list',
      name: 'name',
      message: 'Please select the employee whose role needs updating:',
      choices: employee,
    },
    {
      type: 'list',
      name: 'role_id',
      message: 'Please select the new role for the selected employee:',
      choices: role
    },
    {
      type: 'list',
      name: 'manager_id',
      message: 'Please update the manager for the selected employee:',
      choices: manager
    },
  ];
  // Create variables for each user response from prompts
  const { name, role_id, manager_id } = await inquirer.prompt(questions);
  // Update the employee data with the input from the user
  await query(
    'UPDATE employee SET role_id = ?, manager_id = ? WHERE id = ?',
    [role_id, manager_id, name]
  );
  // Display the employees table to show updates and return to the main menu
  viewAllEmployees();
}

async function viewAllRoles() {
  // Add to query to join department names instead of having the department id in the table
  const result = await query(`SELECT role.id, title, department.name AS department, salary FROM role JOIN department ON department.id = role.department_id`);
  // Display the table
  console.table(result);
  // Return to main menu
  init();
}

// Create addRole function
async function addRole() {
  // Add query to get department names and their id with an alias of value to work with inquirer
  const department = await query(`SELECT id AS value, name FROM department`);
  const questions = [
    {
      type: 'input',
      name: 'title',
      message: 'Please enter the name of the new role:',
    },
    {
      type: 'input',
      name: 'salary',
      message: `Please enter the new role's salary:`,
    },
    {
      type: 'list',
      name: 'department_id',
      message: `Please enter the new role's department:`,
      choices: department,
    },
  ];
  // Create variables of user input from prompts
  const { title, salary, department_id } = await inquirer.prompt(questions);
  
  // Insert user input into the table
  await query(
    `INSERT INTO role (title, salary, department_id) VALUES(?, ?, ?)`,
    [title, salary, department_id]
  );
  // Display a success message
  console.log(`${title} has been added to the database!`);
  // Show the table with the updates and return to the main menu
  viewAllRoles();
}

// Create viewAllDepartments function
async function viewAllDepartments() {
  // Create variable to store query
  const result = await query(`SELECT * FROM department`);
  // Display the table
  console.table(result);
  // Return to main menu
  init();
}

// Create addDepartment function
async function addDepartment() {
  // Define questions
  const questions = [
    {
      type: 'input',
      name: 'name',
      message: 'Please enter the name of the new department:'
    },
  ];
  // Create variable of user input from the prompt
  const { name } = await inquirer.prompt(questions);

  // Insert the user input into the table
  await query(
    `INSERT INTO department (name) VALUES (?)`,
    [name]
    );
  // Display a success message
  console.log(`Added ${name} to the database!`);
  // Show the table with the changes and return to main menu
  viewAllDepartments();
}


init();